<template>
    <v-data-table :headers="headers" :items="table === '1' ? table1 : table === '2' ? table2 : table3"
                  class="elevation-2" hide-actions :loading="!loaded">
        <template v-slot:items="props">
            <td>{{ props.item.name }}</td>
            <td>{{ props.item.jan }}</td>
            <td>{{ props.item.feb }}</td>
            <td>{{ props.item.mar }}</td>
            <td>{{ props.item.apr }}</td>
            <td>{{ props.item.may }}</td>
            <td>{{ props.item.jun }}</td>
            <td>{{ props.item.jul }}</td>
            <td>{{ props.item.aug }}</td>
            <td>{{ props.item.sep }}</td>
            <td>{{ props.item.oct }}</td>
            <td>{{ props.item.nov }}</td>
            <td>{{ props.item.dec }}</td>
        </template>
        <template v-slot:no-data>
            <v-alert :value="true" color="error" icon="warning">
                Здесь ничего нет.
            </v-alert>
        </template>
        <template v-slot:footer>
            <td :colspan="headers.length">
                Тестовая таблица #{{table}}
            </td>
        </template>
    </v-data-table>
</template>

<script>
    export default {
        name: "apptable",
        props: ['table', 'loaded'],
        data() {
            return {
                headers: [
                    {text: 'Имя критерия', value: 'name'},
                    {text: 'Январь', value: 'jan'},
                    {text: 'Февраль', value: 'feb'},
                    {text: 'Март', value: 'mar'},
                    {text: 'Аперль', value: 'apr'},
                    {text: 'Май', value: 'may'},
                    {text: 'Июнь', value: 'jun'},
                    {text: 'Июль', value: 'jul'},
                    {text: 'Август', value: 'aug'},
                    {text: 'Сентябрь', value: 'sep'},
                    {text: 'Октябрь', value: 'oct'},
                    {text: 'Ноябрь', value: 'nov'},
                    {text: 'Декабрь', value: 'dec'},

                ],
                table1: [
                    {
                        name: 'Критерий #1',
                        jan: 1590,
                        feb: 6000,
                        mar: 2400,
                        apr: 4000,
                        may: 1400,
                        jun: 1290,
                        jul: 6000,
                        aug: 2600,
                        sep: 4800,
                        oct: 7000,
                        nov: 9830,
                        dec: 1200,
                    },
                    {
                        name: 'Критерий #2',
                        jan: 17590,
                        feb: 50700,
                        mar: 24800,
                        apr: 88000,
                        may: 91400,
                        jun: 31290,
                        jul: 36000,
                        aug: 42600,
                        sep: 24800,
                        oct: 57000,
                        nov: 19830,
                        dec: 71200,
                    },
                    {
                        name: 'Критерий #3',
                        jan: 35690,
                        feb: 67500,
                        mar: 257400,
                        apr: 774000,
                        may: 981400,
                        jun: 561290,
                        jul: 346000,
                        aug: 682600,
                        sep: 454800,
                        oct: 247000,
                        nov: 919830,
                        dec: 41200,
                    },
                    {
                        name: 'Критерий #4',
                        jan: 22590,
                        feb: 34000,
                        mar: 75400,
                        apr: 678000,
                        may: 56400,
                        jun: 45290,
                        jul: 98000,
                        aug: 70600,
                        sep: 45800,
                        oct: 30000,
                        nov: 34830,
                        dec: 13200,
                    },
                    {
                        name: 'Критерий #1',
                        jan: 1590,
                        feb: 6000,
                        mar: 2400,
                        apr: 4000,
                        may: 1400,
                        jun: 1290,
                        jul: 6000,
                        aug: 2600,
                        sep: 4800,
                        oct: 7000,
                        nov: 9830,
                        dec: 1200,
                    },
                    {
                        name: 'Критерий #2',
                        jan: 17590,
                        feb: 50700,
                        mar: 24800,
                        apr: 88000,
                        may: 91400,
                        jun: 31290,
                        jul: 36000,
                        aug: 42600,
                        sep: 24800,
                        oct: 57000,
                        nov: 19830,
                        dec: 71200,
                    },
                    {
                        name: 'Критерий #3',
                        jan: 35690,
                        feb: 67500,
                        mar: 257400,
                        apr: 774000,
                        may: 981400,
                        jun: 561290,
                        jul: 346000,
                        aug: 682600,
                        sep: 454800,
                        oct: 247000,
                        nov: 919830,
                        dec: 41200,
                    },
                    {
                        name: 'Критерий #4',
                        jan: 22590,
                        feb: 34000,
                        mar: 75400,
                        apr: 678000,
                        may: 56400,
                        jun: 45290,
                        jul: 98000,
                        aug: 70600,
                        sep: 45800,
                        oct: 30000,
                        nov: 34830,
                        dec: 13200,
                    },
                    {
                        name: 'Критерий #1',
                        jan: 1590,
                        feb: 6000,
                        mar: 2400,
                        apr: 4000,
                        may: 1400,
                        jun: 1290,
                        jul: 6000,
                        aug: 2600,
                        sep: 4800,
                        oct: 7000,
                        nov: 9830,
                        dec: 1200,
                    },
                    {
                        name: 'Критерий #2',
                        jan: 17590,
                        feb: 50700,
                        mar: 24800,
                        apr: 88000,
                        may: 91400,
                        jun: 31290,
                        jul: 36000,
                        aug: 42600,
                        sep: 24800,
                        oct: 57000,
                        nov: 19830,
                        dec: 71200,
                    },
                    {
                        name: 'Критерий #3',
                        jan: 35690,
                        feb: 67500,
                        mar: 257400,
                        apr: 774000,
                        may: 981400,
                        jun: 561290,
                        jul: 346000,
                        aug: 682600,
                        sep: 454800,
                        oct: 247000,
                        nov: 919830,
                        dec: 41200,
                    },
                    {
                        name: 'Критерий #4',
                        jan: 22590,
                        feb: 34000,
                        mar: 75400,
                        apr: 678000,
                        may: 56400,
                        jun: 45290,
                        jul: 98000,
                        aug: 70600,
                        sep: 45800,
                        oct: 30000,
                        nov: 34830,
                        dec: 13200,
                    },
                    {
                        name: 'Критерий #1',
                        jan: 1590,
                        feb: 6000,
                        mar: 2400,
                        apr: 4000,
                        may: 1400,
                        jun: 1290,
                        jul: 6000,
                        aug: 2600,
                        sep: 4800,
                        oct: 7000,
                        nov: 9830,
                        dec: 1200,
                    },
                    {
                        name: 'Критерий #2',
                        jan: 17590,
                        feb: 50700,
                        mar: 24800,
                        apr: 88000,
                        may: 91400,
                        jun: 31290,
                        jul: 36000,
                        aug: 42600,
                        sep: 24800,
                        oct: 57000,
                        nov: 19830,
                        dec: 71200,
                    },
                    {
                        name: 'Критерий #3',
                        jan: 35690,
                        feb: 67500,
                        mar: 257400,
                        apr: 774000,
                        may: 981400,
                        jun: 561290,
                        jul: 346000,
                        aug: 682600,
                        sep: 454800,
                        oct: 247000,
                        nov: 919830,
                        dec: 41200,
                    },
                    {
                        name: 'Критерий #4',
                        jan: 22590,
                        feb: 34000,
                        mar: 75400,
                        apr: 678000,
                        may: 56400,
                        jun: 45290,
                        jul: 98000,
                        aug: 70600,
                        sep: 45800,
                        oct: 30000,
                        nov: 34830,
                        dec: 13200,
                    }
                ],
                table2: [
                    {
                        name: 'Критерий #1',
                        jan: 2590,
                        feb: 2000,
                        mar: 2400,
                        apr: 2000,
                        may: 2400,
                        jun: 2290,
                        jul: 2000,
                        aug: 2600,
                        sep: 2800,
                        oct: 2000,
                        nov: 2830,
                        dec: 2200,
                    },
                    {
                        name: 'Критерий #2',
                        jan: 17590,
                        feb: 50700,
                        mar: 24800,
                        apr: 88000,
                        may: 91400,
                        jun: 31290,
                        jul: 36000,
                        aug: 42600,
                        sep: 24800,
                        oct: 57000,
                        nov: 19830,
                        dec: 71200,
                    },
                    {
                        name: 'Критерий #3',
                        jan: 35690,
                        feb: 67500,
                        mar: 257400,
                        apr: 774000,
                        may: 981400,
                        jun: 561290,
                        jul: 346000,
                        aug: 682600,
                        sep: 454800,
                        oct: 247000,
                        nov: 919830,
                        dec: 41200,
                    },
                    {
                        name: 'Критерий #4',
                        jan: 22590,
                        feb: 34000,
                        mar: 75400,
                        apr: 678000,
                        may: 56400,
                        jun: 45290,
                        jul: 98000,
                        aug: 70600,
                        sep: 45800,
                        oct: 30000,
                        nov: 34830,
                        dec: 13200,
                    },
                ],
                table3: [
                    {
                        name: 'Критерий #1',
                        jan: 3590,
                        feb: 3000,
                        mar: 3400,
                        apr: 3000,
                        may: 3400,
                        jun: 3290,
                        jul: 3000,
                        aug: 3600,
                        sep: 3800,
                        oct: 3000,
                        nov: 3830,
                        dec: 3200,
                    },
                    {
                        name: 'Критерий #2',
                        jan: 17590,
                        feb: 50700,
                        mar: 24800,
                        apr: 88000,
                        may: 91400,
                        jun: 31290,
                        jul: 36000,
                        aug: 42600,
                        sep: 24800,
                        oct: 57000,
                        nov: 19830,
                        dec: 71200,
                    },
                    {
                        name: 'Критерий #3',
                        jan: 35690,
                        feb: 67500,
                        mar: 257400,
                        apr: 774000,
                        may: 981400,
                        jun: 561290,
                        jul: 346000,
                        aug: 682600,
                        sep: 454800,
                        oct: 247000,
                        nov: 919830,
                        dec: 41200,
                    },
                    {
                        name: 'Критерий #4',
                        jan: 22590,
                        feb: 34000,
                        mar: 75400,
                        apr: 678000,
                        may: 56400,
                        jun: 45290,
                        jul: 98000,
                        aug: 70600,
                        sep: 45800,
                        oct: 30000,
                        nov: 34830,
                        dec: 13200,
                    },
                ]
            }
        }
    }
</script>

<style scoped>

</style>
